name: gis
description: "GIS Mobile App Project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  dart_shp: ^1.2.0
  flutter:
    sdk: flutter
  shapefile: ^1.0.1
  path_provider: ^2.1.5
  cupertino_icons: ^1.0.8
  flutter_map: ^6.0.0
  latlong2: 0.9.1
  flutter_map_geojson: ^1.0.8
  firebase_core: ^3.11.0
  firebase_database: ^11.2.0
  firebase_auth: ^5.4.2
  cloud_firestore: ^5.6.3
  intl_phone_number_input: ^0.7.4
  firebase_phone_auth_handler: ^1.1.0
  recaptcha_enterprise_flutter: ^18.6.1
  firebase_app_check: ^0.3.2+2
  g_recaptcha_v3: ^1.0.0
  crypto: ^3.0.6
  shared_preferences: ^2.3.5
  image_picker: ^1.1.2
  sqflite: ^2.4.1
  geolocator: ^13.0.2
  webview_flutter_android: ^4.3.1
  webview_flutter: ^4.10.0
  carousel_slider: ^5.0.0
  camera: ^0.11.1
  permission_handler: ^11.3.1
  dropdown_button2: ^2.3.9
  firebase_storage: ^12.4.2
  cloudinary_public: ^0.23.1
  lottie: ^3.3.1
  twilio_flutter: ^0.9.0
  socket_io_client: ^3.0.2
  flutter_local_notifications: ^18.0.1
  http: ^1.3.0
  mongo_dart: ^0.10.4
  intl: ^0.20.2
  file_picker: ^9.0.0
  google_maps_flutter: ^2.10.0
  mapbox_maps_flutter: ^2.6.0
  get: ^4.7.2
  url_launcher: ^6.3.1
  photo_view: ^0.15.0
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo_icon_GIS.jpg"

flutter:
  uses-material-design: true
  assets:
   - assets/
   - assets/img1.jpg
   - assets/img2.jpg
   - assets/img3.jpg
   - assets/img4.jpg
   - assets/img5.jpg
   - assets/basins_tumun.json
   - assets/lands_tumun.json
   - assets/basins_turmus_aia.json
   - assets/lands_turmus_aia.json
  fonts:
    - family: IBM_Bold
      fonts:
        - asset: assets/fonts/IBMPlexSansArabic-Bold.ttf
    - family: IBM_Regular
      fonts:
        - asset: assets/fonts/IBMPlexSansArabic-Regular.ttf
    - family: IBM_Light
      fonts:
        - asset: assets/fonts/IBMPlexSansArabic-Light.ttf
    - family: IBM_SemiBold
      fonts:
        - asset: assets/fonts/IBMPlexSansArabic-SemiBold.ttf